"""Duas cocheiras e limites

Revision ID: 78c1accc5851
Revises: 
Create Date: 2026-08-17 14:25:19.328597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c1accc5851'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_sal_cocho', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tem_cocho_racao', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('qtd_racao_cocho', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.drop_column('qtd_racao_cocho')
        batch_op.drop_column('tem_cocho_racao')
        batch_op.drop_column('qtd_sal_cocho')

    # ### end Alembic commands ###
